resources: !include lovelace/resources/resources.yaml
custom_header: !include lovelace/custom_header/custom_header.yaml

title: Home
background: var(--background-image)
popup_cards: !include lovelace/templates/legacy_popup_cards.yaml
views: !include_dir_merge_list lovelace/views/
  