### Philips Hue dimmers for use with deCONZ
### The icons in the description are the icons
### shown on the actual remote for convenience

## Livingroom

# Button 1 tap_action (power-on icon)
- alias: 'Livingroom Philips button 1 tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_woonkamer_muur
      event: 1002
  action:
    service: light.turn_on
    entity_id: 
      - light.woonkamer
      - light.woonkamer_led_lampen

# Button 1 hold_action (power-on icon)
- alias: 'Livingroom Philips button 1 hold_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_woonkamer_muur
      event: 1001
  action:
    - service: light.turn_on
      entity_id: 
        - light.woonkamer_led_lampen
        - light.vloerlamp
        - light.tafellamp
    - service: light.turn_off
      entity_id:
        - light.plafond
        - light.eettafel

# Button 2 hold_action (brightness-up icon)
- alias: 'Livingroom Philips button 2 hold_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_woonkamer_muur
      event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.woonkamer
        brightness: >
          {% set bri = state_attr('light.woonkamer', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

# Button 3 hold_action (brightness-down icon)
- alias: 'Livingroom Philips button 3 hold_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_woonkamer_muur
      event: 3001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.woonkamer
        brightness: >
          {% set bri = state_attr('light.woonkamer', 'brightness') | int %}
          {{ [bri-30, 0] | max }}

# Button 4 tap_action (power-off icon)
- alias: 'Livingroom Philips button 4 tap_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_woonkamer_muur
      event: 4002
  action:
    service: light.turn_off
    entity_id: 
      - light.woonkamer

# Button 4 hold_action (power-off icon)
- alias: 'Livingroom Philips button 4 hold_action'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ab_woonkamer_muur
      event: 4001
  action:
    service: light.turn_off
    entity_id: 
      - light.woonkamer_led_lampen
