# Main Lovelace Config

## Button Card Templates
button_card_templates: !include_dir_named templates/button/templates/

## Swipe Navigation, you can enable this by downloading the lovelace-swipe-navigation card from HACS and uncomment the lines below

# swipe_nav:
#   wrap: true
#   animate: fade
#   skip_hidden: false
#   skip_tabs: 2,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
#   prevent_default: true
#   swipe_amount: 30

## Base Configuration
title: Home
background: var(--background-image)
popup_cards: !include templates/popups/legacy-popups.yaml
views: 
  !include base.yaml