- title: HKI Settings
  path: hki_settings_air_visual
  cards:    
    - type: vertical-stack
      cards:
        - !include
          - '../../templates/system_header_advanced.yaml'
          - name: Air Visual
            icon: mdi:weather-windy
            content: "HKI {{ states.input_text.name_header_settings.state }}"
            system_header: input_boolean.config_header
        - type: conditional
          conditions:
            - entity: input_boolean.edit_mode
              state: "on"
          card:
            !include
            - '../../templates/edit_mode_warning.yaml'
            - template: nothing_to_edit.yaml
        - !include
          - '../../templates/settings_back_button.yaml'
          - background_color: LightSeaGreen
        - type: custom:search-card
          style: |
            ha-card {
              border-radius: none;
              box-shadow: none;
              --paper-card-background-color: rgba(0,0,0,0.0);
              --primary-text-color: var(--category-text) !important;
              color: var(--category-text) !important;
              --text-primary-color: var(--category-text) !important;
              --secondary-text-color: var(--category-text) !important;
              --disabled-text-color: var(--category-text) !important;
            }
          max_results: 10
        - type: horizontal-stack
          cards:
            - !include ../../includes/blank-card.yaml
            - type: custom:layout-card
              cards:
                - type: conditional
                  conditions:
                    - entity: input_boolean.system_help
                      state: "on"
                  card:
                    type: markdown                          
                    style: |
                      ha-card {
                        background: rgba(0, 0, 0, 0.5);
                        border-radius: {{ states('input_select.border_radius') }};
                        box-shadow: {{ states('input_select.box_shadow') }};
                        font-size: 13px;
                        font-family: Helvetica;
                        color: white;
                      }                        
                    content: >
                      **Air Visual:** You can set up Air Visual here. This will be displayed on the weather view and should be turned on with edit mode.
                - type: entities
                  title: Air Visual
                  show_header_toggle: false                          
                  style: |
                    ha-card {
                      border-radius: {{ states('input_select.border_radius') }};
                      box-shadow: {{ states('input_select.box_shadow') }};
                    }                        
                  entities: 
                    - entity: input_text.weather_entity
                      type: 'custom:text-input-row'
                    - entity: input_text.city
                      type: 'custom:text-input-row'
                    - entity: input_text.air_pollution_level
                      type: 'custom:text-input-row'
                    - entity: input_text.air_quality_index
                      type: 'custom:text-input-row'
                    - entity: input_text.main_pollutant
                      type: 'custom:text-input-row'
            - !include ../../includes/blank-card.yaml