lovelace_gen: !include_dir_merge_named ../../global_config/

automation:
## Automations that you can edit
  # Frontend Header Greeting (If you change this, change the input_select for this as well, use the same names!)
  - alias: Frontend Greeting
    trigger:
      - platform: time_pattern
        minutes: "/5"
      - platform: homeassistant
        event: start
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.frontend_greeting
        option: >
          {% if (states.sensor.time.state > '00:00') and (states.sensor.time.state < '06:00') %}
            Good Night
          {% elif (states.sensor.time.state > '06:00') and (states.sensor.time.state < '12:00') %}
            Good Morning
          {% elif (states.sensor.time.state > '12:00') and (states.sensor.time.state < '18:00') %}
            Good Afternoon
          {% elif (states.sensor.time.state > '18:00') and (states.sensor.time.state < '23:59') %}
            Good Evening
          {% endif %}
  
  #####################################################################################################
  ## Automations that you should NOT touch!
  
  # State Change Automations used for device counting
  - alias: 'group state change'
    id: 'State changed'
    trigger:
      platform: event
      event_type: state_changed
    condition: 
      condition: or
      conditions:
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_lighting','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_device_switches','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_radiator_valves','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_computers','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_tvs','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_binary_sensors','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_laundry_devices','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_door_sensors','entity_id') }}
        - condition: template
          value_template: >
            {{ trigger.event.data.entity_id in state_attr('group.all_window_sensors','entity_id') }}
    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_lights_on
        - sensor.current_devices_on
        - sensor.current_radiator_valves_on
        - sensor.current_computers_on
        - sensor.current_tvs_on
        - sensor.current_laundry_devices_on
        - sensor.current_sensors_on
        - sensor.current_doors_open
        - sensor.current_windows_open
        - sensor.current_binary_sensors_on
  
  # Theme Selector
  - alias: 'themes'
    initial_state: 'true'
    trigger:
      - platform: state
        entity_id: input_select.theme_selector
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sun.sun
      - platform: state
        entity_id: sensor.anniversary_anniversary
        to: '0'
    action:
      - service: frontend.set_theme
        data_template:
          name: >
            {% if is_state('input_select.theme_selector', 'Silver') %}
              Silver
            {% elif is_state('input_select.theme_selector', 'Space Gray') %}
              Space Gray
            {% elif is_state('input_select.theme_selector', 'Sweet Pink') %}
              Sweet Pink
            {% elif is_state('input_select.theme_selector', 'Valentine') %}
              Valentine
            {% elif is_state('input_select.theme_selector', 'Default HA') %}
              default
            {% elif (is_state('sensor.anniversary_anniversary', '0')) and (is_state('input_select.theme_selector', 'Auto'))  %}
              Valentine
            {% elif (is_state('sun.sun', 'above_horizon')) and (is_state('input_select.theme_selector', 'Auto'))  %}
              Silver
            {% elif (is_state('sun.sun', 'below_horizon')) and (is_state('input_select.theme_selector', 'Auto'))  %}
              Space Gray
            {% elif is_state('input_select.theme_selector', 'Auto') %}
              Space Gray
            {% endif %}
  
  # Box Shadow Selector
  - alias: input select beautifier box-shadow
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: input_select.box_shadow_selector
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.box_shadow
        option: >
          {% if is_state('input_select.box_shadow_selector', 'None') %}
            none
          {% elif is_state('input_select.box_shadow_selector', 'Small') %}
            1px 1px 1px 0px rgba(0,0,0,0.75)
          {% elif is_state('input_select.box_shadow_selector', 'Standard') %}
            2px 2px 2px 0px rgba(0,0,0,0.75)
          {% elif is_state('input_select.box_shadow_selector', 'Large') %}
            5px 5px 5px 0px rgba(0,0,0,0.75)
          {% endif %}
  
  # Border Radius Selector
  - alias: input select beautifier border-radius
    initial_state: 'true'
    trigger:
    - platform: state
      entity_id: input_select.border_radius_selector
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.border_radius
        option: >
          {% if is_state('input_select.border_radius_selector', 'None') %}
            0px
          {% elif is_state('input_select.border_radius_selector', 'Small') %}
            6px
          {% elif is_state('input_select.border_radius_selector', 'Standard') %}
            12px
          {% elif is_state('input_select.border_radius_selector', 'Large') %}
            18px
          {% endif %}
  
input_boolean:
  # Other
  dummy1:
    initial: off
  dummy2:
    initial: off

# Required input_selects for HKI to work properly
input_select:
# Frontend Greeting (shown in the header of the frontpage)
  frontend_greeting:
    name: Frontend Greeting
    options:
      - Good Morning
      - Good Afternoon
      - Good Evening
      - Good Night
  
  # The theme selector used to show in the interface
  theme_selector:
    name: Theme Selector 
    options:
      - Silver
      - Space Gray
      - Sweet Pink
      - Valentine
      - Default HA
      - Auto
  
  # Border Radius used in border-radius templates,
  # you can adjust border size to be selected here
  border_radius:
    name: Border Radius
    options:
      - 0px
      - 6px
      - 12px
      - 18px
  
  # Border Radius selector to show in the interface
  border_radius_selector:
    name: Border Radius Selector
    options:
      - None 
      - Small
      - Standard
      - Large
  
  # Box Shadow used in box-shadow templates, you can adjust
  # how the box shadow looks in here
  box_shadow:
    name: Box Shadow
    options:
      - none
      - 1px 1px 1px 0px rgba(0,0,0,0.75)
      - 2px 2px 2px 0px rgba(0,0,0,0.75)
      - 5px 5px 5px 0px rgba(0,0,0,0.75)
   
  # Box Shadow selector to show in the interface
  box_shadow_selector:
    name: Box Shadow Selector
    options:
      - None
      - Small
      - Standard
      - Large
  
  # Person Menu 1 (used for personal views)
  person_menu_1:
    name: Person Menu 1 Selector
    options:
      - Overview
      - Calendar
      - Location
      - Vehicle
    initial: Overview
  
  # Person Menu 2 (used for personal views)
  person_menu_2:
    name: Person Menu 2 Selector
    options:
      - Overview
      - Calendar
      - Location
      - Vehicle
    initial: Overview
  
  # Person Menu 3 (used for personal views)
  person_menu_3:
    name: Person Menu 3 Selector
    options:
      - Overview
      - Calendar
      - Location
      - Vehicle
    initial: Overview
  
  # Person Menu 4 (used for personal views)
  person_menu_4:
    name: Person Menu 4 Selector
    options:
      - Overview
      - Calendar
      - Location
      - Vehicle
    initial: Overview
  
  # Xiaomi Vacuum
  xiaomi_vacuum:
    name: Xiaomi Vacuum
    options:
      - Silent
      - Standard
      - Medium
      - Turbo
      - Gentle

### Notification Badge Templates (needed for the badges to appear on buttons!)
### Please do NOT touch this!!!!
sensor:
  - platform: template
    sensors:
      current_lights_on:
        friendly_name: All Lights Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_lighting','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_devices_on:
        friendly_name: All Devices Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_device_switches','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_sensors_on:
        friendly_name: All Sensors Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_motion_smoke_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_binary_sensors_on:
        friendly_name: All Binary Sensors Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_binary_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_doors_open:
        friendly_name: All Doors Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_door_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_windows_open:
        friendly_name: All Windows Currently Open
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_window_sensors','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_radiator_valves_on:
        friendly_name: All Radiator Valves Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_radiator_valves','entity_id'))|selectattr('state','eq','heat')|list|count }}
      current_computers_on:
        friendly_name: All Computers Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_computers','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_tvs_on:
        friendly_name: All TV's Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_tvs','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_laundry_devices_on:
        friendly_name: All Laundry Devices Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_laundry_devices','entity_id'))|selectattr('state','eq','on')|list|count }}
      current_scenes_on:
        friendly_name: All Scenes
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.all_scenes','entity_id'))|selectattr('state','eq','on')|list|count }}    
