# Notify Jimmy/Stephanie when arrive home
- alias: Jimmy Home Alert
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: person.jimmy
    from: 'not_home'
    to: 'home'
    for:
      seconds: 60
  action:
  - service: notify.mobile_app_iphone_stephanie
    data:
      title: "Locatie"
      message: "Jimmy is zojuist Thuis gearriveerd"
      data:
        push:
          sound: default
          category: map
        action_data:
          latitude: !secret latitude1
          longitude: !secret longitude1

- alias: Stephanie Home Alert
  initial_state: 'true'
  trigger:
  - platform: state
    entity_id: person.stephanie
    to: 'home'
    for:
      seconds: 60
  action:
  - service: notify.mobile_app_iphone
    data:
      title: "Locatie"
      message: "Stephanie is zojuist Thuis gearriveerd"
      data:
        push:
          badge: 0
          sound: default
          category: map
        action_data:
          latitude: !secret latitude1
          longitude: !secret longitude1